modified donate button in popup for closed hospital
digitalaidseattle/games-for-love pull request #14
Opened 2024-08-20 07:21 UTC by MayHyeyeonKim

## Description
- Following our discussion in the last meeting, I’ve **removed the Donate button from the popup for the closed hospital**. 
- Additionally, just in case, I adjusted **the color of the marker in the location chip based on the hospital's status** ('Closed' or 'Actively funding'). If you'd prefer to revert to the previous green color, please let me know. :)

![Screenshot 2024-08-19 at 11 47 32 PM](https://github.com/user-attachments/assets/1bce6ed1-0422-46d1-8c69-d834f0f069ff)

- Code sections where the **marker chip color** to the left of the address changes **based on the hospital's status**.  
<img width="736" alt="Screenshot 2024-08-20 at 12 06 12 AM" src="https://github.com/user-attachments/assets/181465da-36c8-42c6-b5d0-13f279150243">

<br>
<br>

- Code sections where the presence of the **Donate button** is toggled **based on the hospital's status**.  
<img width="617" alt="Screenshot 2024-08-20 at 12 06 31 AM" src="https://github.com/user-attachments/assets/7df9a05d-b049-4cc0-96c9-39ac7c697d8a">

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

_Link user story from projects.digitalaidseattle.org_

- This PR is a revision of Mayk/popup2 #12

## QA Instructions, Screenshots, Recordings
Mayk/popup2 #12 QA Instructions +
**Closed hospitals** should have only the **'Learn more' button**, while **actively funding hospitals** should have both **'Learn more' and 'Donate' buttons**.

2024-08-20 18:39 UTC, jnakaso requested changes
Simple things we can add to improve code quality.

2024-08-20 18:39 UTC, jnakaso commented on src/components/cards/HospitalCard.tsx
This line
```
${popupInfo?.hospitalInfo?.status}` !== "Closed"
```
is repeated multiple times in this file.  For **maintainability** and **readability**, assign the value to a local variable.

```
const isOpen = popupInfo?.hospitalInfo?.status !== "Closed";
const pinColor = isOpen ? "#92C65E" : "#DB5757";
const buttonWidth =  isOpen ? "112px" : "300px";
```

To go even a step further, a function in the hospitalInfoService could be added that would encapsulate the behavior and provide data hiding. 

```
function isOpen(hospitalInfo: HospitalInfo) {
    // throw an exception if hospitalInfo is undefined ?
    return hospitalInfo?.status !== "Closed"
}
```

At some point we will want to make an object to contain color info so that  "#92C65E" &  "#DB5757" are place by a reference like OPEN_PIN_COLOR and CLOSED_PIN_COLOR

2024-08-20 20:15 UTC, MayHyeyeonKim commented on src/components/cards/HospitalCard.tsx
Wow!! Thank you for letting me know these advanced skills!😃 
I applied the two methods you suggested + I also elevated reusability by defining the color variables in the theme. 

There are three commits, each addressing these changes separately. (I would appreciate it if you could review each of the commits.)
I'm really lucky to be able to learn so much from you! 👍👍👍

2024-08-20 20:33 UTC, jnakaso commented on src/services/hospitalInfo/hospitalInfoService.ts
> +function isHospitalOpen(hospitalInfo: HospitalInfo | undefined) {
I would move this function into the service.

then change MockHospitalInfoService to
```
class MockHospitalInfoService extends HospitalInfoService
```

Do forget to write a test for this new function :-)

2024-08-20 20:40 UTC, jnakaso commented on src/styles/theme.ts
Nice!

2024-08-20 20:43 UTC, jnakaso commented on src/components/cards/HospitalCard.tsx
looks good

2024-08-20 20:47 UTC, jnakaso requested changes
Looks really good.  As a reminder, write unit tests for service functions.

2024-08-21 07:52 UTC, jnakaso approved these changes
Thank you for including the test!

2024-08-21 15:05 UTC, merged