Mayk/filter2
digitalaidseattle/games-for-love pull request #19
Opened 2024-09-17 23:36 UTC by MayHyeyeonKim

## Description
I implemented the filters dialog. 
For **Location**, users can enter a **city, state, or zip code (case-insensitive)**. When the Enter key is pressed, a **chip** is created below. 
For **Status**, users can select **'active,' 'past,' or 'all.'** After clicking the **'Apply filters'** button, data is fetched from the `hospitalInfoService`, displaying the relevant filtered data.

### ui
![Screenshot 2024-09-17 at 4 22 33 PM](https://github.com/user-attachments/assets/bc3e245f-29b9-402d-8a95-bcf6c7da7b27)

![Screenshot 2024-09-17 at 4 07 07 PM](https://github.com/user-attachments/assets/8aea23f5-2a3b-420b-b1a0-703a90c39571)

### Filtering in the hospitalInfoService
<img width="721" alt="Screenshot 2024-09-17 at 4 19 49 PM" src="https://github.com/user-attachments/assets/4d73fc80-0fcf-4495-aef3-6ec6b8550eb1">

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents
[1.1.3.1 Display filter criteria on the map UI](https://projects.digitalaidseattle.org/project-tasks-details?recordId=rec8bckzXGKMi88Tp)
[1.1.3.4 Upgrade hospital-service to take filter criteria and return filtered result](https://projects.digitalaidseattle.org/project-tasks-details?recordId=recQy58l8ioOY668n)
[1.1.3.5 Define hospital-service API for filter functionality](https://projects.digitalaidseattle.org/project-tasks-details?recordId=recgCDMmh4I9dWX3H)

## QA Instructions, Screenshots, Recordings

**1. Location Filter:**

Enter a city, state, or zip code in the Location field.
Press Enter to create a chip for the entered criteria.
Ensure chips are displayed correctly below the input.

**2. Status Filter:**

Select 'active,' 'past,' or 'all' from the Status dropdown.
Verify the selected status is correctly highlighted.

**3. Apply Filters:**

Click the 'Apply filters' button.
Confirm that data is fetched from hospitalInfoService and displays the filtered results.

**4. UI Testing:**

Check the UI for responsiveness and correct rendering based on the screenshots provided.
Ensure that when there are many chips, a scrollbar appears, indicating proper handling of overflow.

**5. Error Handling:**

Note that error handling has not yet been implemented.

**6. Discussion Points:**

Observe the behavior when many chips are added.
Determine if there is a need to limit the number of chips through further discussion with the team and the client.

2024-09-24 05:43 UTC, jnakaso commented
Here are changes that should be implemented:
- The filter component needs to store state of users selections  (i.e. if the user types in a location, the next time filter dialog is opened, the location should be displayed.)

2024-09-26 08:13 UTC, MayHyeyeonKim commented
> Here are changes that should be implemented:
> 
> * The filter component needs to store state of users selections  (i.e. if the user types in a location, the next time filter dialog is opened, the location should be displayed.)
> * context for Hospitals  (see useContext)  This will simplify the codebase quite a bit by not having to pass hospitals as a argument to every component.  I can show how this can be done.

Thank you for showing me how to use useContext, I just modified that the part and commited it again.
I also saw that you implemented the search functionality in `hospitalInfoService`. It's working well too! 😊👍

2024-10-03 09:03 UTC, MayHyeyeonKim commented
added `Clear all` button
<img width="1416" alt="Screenshot 2024-10-03 at 1 47 44 AM" src="https://github.com/user-attachments/assets/f275b498-1171-40c5-99f0-bb5618a4d573">

2024-10-04 17:34 UTC, jnakaso requested changes
Please address various comments

2024-10-06 06:32 UTC, MayHyeyeonKim commented on src/components/GFLMap.tsx
> +          color={hospital.status === "past" ? "#DB5757" : "#92C65E"}
[question]
I set the status in `hospitalInfo` as a union type (`"active"` | `"past"`). However, in `thumbnailData`, I set the status of an entry to `"blabla"`. Why doesn't it throw an error even though the status in `hospitalInfo` is not one of `"active"` or `"past"`?

[Does this commit align with the method you suggested?](https://github.com/digitalaidseattle/games-for-love/pull/19/commits/d73481c88d61ad7cce456414139f59277f9a3d88)

2024-10-06 06:42 UTC, MayHyeyeonKim commented on src/components/Filter.tsx
https://github.com/digitalaidseattle/games-for-love/pull/19/commits/da8999e2584c661a2204552840eb8ac7f2eff7ea

2024-10-06 06:42 UTC, MayHyeyeonKim commented on src/components/Filter.tsx
> +interface FilterProps {
https://github.com/digitalaidseattle/games-for-love/pull/19/commits/da8999e2584c661a2204552840eb8ac7f2eff7ea

2024-10-06 06:42 UTC, MayHyeyeonKim commented on src/components/Filter.tsx
> +const BootstrapDialog = styled(Dialog)(() => ({
https://github.com/digitalaidseattle/games-for-love/pull/19/commits/da8999e2584c661a2204552840eb8ac7f2eff7ea

2024-10-06 06:58 UTC, MayHyeyeonKim commented on src/context/HospitalsContext.tsx
https://github.com/digitalaidseattle/games-for-love/pull/19/commits/a1dfa4c6bd130883b167982e7ade5b4b9b8df538

2024-10-06 07:05 UTC, MayHyeyeonKim commented on src/services/hospitalInfo/hospitalInfoService.ts
>    async getHospitalInfo(): Promise<HospitalInfo[]> {
[Is it right?](https://github.com/digitalaidseattle/games-for-love/pull/19/commits/bfeef52f55cd70b0087ec80fee308c18db9f29cb)

2024-10-06 07:15 UTC, MayHyeyeonKim commented on src/components/Filter.tsx
> +interface FilterProps {
I couldnt understand. Could you plz explain it again?

2024-10-07 15:43 UTC, jnakaso commented on src/components/Filter.tsx
> +interface FilterProps {
Imagine we needed a SortOptionsDialog or HospitalInfoDialog.  The type for the dialog could look like  :

```
 interface SortOptionsDialogProps {
   open: boolean;
   handleClose: () => void;
 }
 
 const SortOptionsDialog: React.FC<SortOptionsDialogProps>

 interface HospitalInfoDialogProps {
   open: boolean;
   handleClose: () => void;
 }
 
 const HospitalInfoDialog: React.FC<HospitalInfoDialogProps>
```

The code could be refactored to look like

```
 interface DialogProps {
   open: boolean;
   handleClose: () => void;
 }
 
 const SortOptionsDialog: React.FC<DialogProps> 
 
 const HospitalInfoDialog: React.FC<DialogProps>
```

What we are trying to imply with code is that all of our dialogs behave in a similar manor.

2024-10-07 20:29 UTC, MayHyeyeonKim commented on src/components/Filter.tsx
> +interface FilterProps {
<img width="978" alt="Screenshot 2024-10-07 at 1 26 48 PM" src="https://github.com/user-attachments/assets/89653ac3-b995-403b-a653-15c8d649fff6">

https://github.com/digitalaidseattle/games-for-love/pull/19/commits/f6a09b71641a993de07f000014cc5231b69cab74


Thank you so so much!👍👍👍

2024-10-12 00:25 UTC, jnakaso approved these changes
Looks good.  There are some minor changes we should do, but we'll address them later

2024-10-12 00:25 UTC, merged