Origin/sushmita/left toolbar highlight hospital pins
digitalaidseattle/games-for-love pull request #21
Opened 2024-09-24 17:06 UTC by Sushmita-Ghosh

## Description

On clicking the hospital card on the left toolbar , the corresponding hospital marker pin should be highlighted on the map.

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

- Related Issue # https://projects.digitalaidseattle.org/project-tasks-details?recordId=recnMJOVFdSP4F5Mg

## QA Instructions, Screenshots, Recordings

When any of the hospital card is clicked on the left toolbar, the corresponding pin color will turn yellow & the size will increase. If clicked again, the color & size go back to normal. 

When clicked/ highlighted:
![image](https://github.com/user-attachments/assets/9f9d669f-e52a-4bc0-823b-4012e274d0b2)

2024-09-24 17:17 UTC, Sushmita-Ghosh commented
When the highlight gets added - I have changed the color to yellow & increased the size to denote a highlight. If any of these changes need to changed. Please let me know. Thanks!

2024-09-25 00:25 UTC, jnakaso commented
I would add two feature:

1. Center the map on the selected hospital
2. Make the selection exclusive, in other words only the recent selection is highlighted.

2024-09-27 15:17 UTC, jnakaso requested changes

2024-10-11 23:25 UTC, Sushmita-Ghosh commented on src/App.tsx
> +    if (hospitals.length > 0) {
Hi Jeff, I have gone through the changes &  have merged your branch that fixes the features/changes that you had requested. Let me know if there are any pending changes you would like to have for this PR.

2024-10-11 23:56 UTC, jnakaso approved these changes
Looks really good.  Thanks!

2024-10-11 23:57 UTC, jnakaso commented on src/components/GFLMap.tsx
> +      {hospitals.map((hospital) => {
We can address this later.

2024-10-11 23:58 UTC, merged