Mayk/setup connections
digitalaidseattle/games-for-love pull request #7
Opened 2024-07-02 17:39 UTC by MayHyeyeonKim

## Description

Setup backend services and connections to airtable and any other services that the map would need to interface with

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

_Link user story from projects.digitalaidseattle.org_

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well as any relevant images for UI changes._

2024-07-02 18:45 UTC, jnakaso commented
Please how the files can be separated into different sections (i.e. api, components, services, etc.).  Use Slack to start a discussion with other devs.

2024-07-02 18:46 UTC, jnakaso commented
The build is failing.  Use `npm run build` locally before pushing.

2024-07-02 18:49 UTC, jnakaso requested changes
please address individual comments

2024-07-02 18:49 UTC, jnakaso commented on coverage/.tmp/coverage-23.json
please add coverage to .gitignore

2024-07-02 18:49 UTC, jnakaso commented on .env
There needs to be an empty line at the end of the file.

2024-07-02 20:53 UTC, MayHyeyeonKim commented on .env
I added `'no-console': 'error',` in `.eslintrc.cjs` and set `"files.insertFinalNewline": true` in my local environment.

2024-07-03 13:10 UTC, jnakaso approved these changes
This looks good.

Let's consider adding a task for reorganizing files and removing example ones.

2024-07-04 19:45 UTC, jnakaso commented
The data we are getting from GFL has no data in the fields attribute.  Let's followup up with Frank if that is right.

2024-07-04 21:50 UTC, Annysah commented
> The data we are getting from GFL has no data in the fields attribute. Let's followup up with Frank if that is right.

Yes, I got undefined.

2024-07-05 23:59 UTC, merged